name: goodproj
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0
  multicast_dns: ^0.3.2+7
  web_socket_channel: ^3.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
